version: '3.8'

services:
    # Laravel App Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis
        environment:
            APP_ENV: local
            APP_DEBUG: true
            APP_KEY: ${APP_KEY}

    # MySQL Database Service
    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_DATABASE: news
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    # Redis Service (optional)
    redis:
        image: redis:6-alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"

volumes:
    db_data:
